### ISSUE TITLE
Dark mode mobile nav does not display "close" icon

### ISSUE THREAD

**Issue by tyreer** [newrelic/opensource-website#596]
# Description

In dark mode, the mobile nav toggle button isn't switching between the hamburger and close icons.

![Screenshot 2020-08-09 at 17 43 52](https://user-images.githubusercontent.com/20293876/89738701-8a525580-da72-11ea-881e-3bce6b32e13e.jpg)

Looks like the rule currently on line 261 in `src/components/Header.module.scss` will never get applied since the `&` on the right would build to the CSS below, which won't match any elements since .dark-mode is applied at the base of the DOM tree on body:

```CSS
div.mobile-menu-active :global(.dark-mode) .mobile-menu-button {
  background-image: url("../images/icon-menu-close-light.svg");
}
```

## Steps to Reproduce

- Open https://opensource.newrelic.com/
- Ensure you're in dark mode
- Make the browser smaller than `725px` or view on a mobile device
- Click the mobile nav "hamburger" icon

Note that the hamburger icon never changes to a "close" icon

## Expected Behavior

When the hamburger menu icon is clicked, a close icon will replace it

## Your Environment

- Browser name and version: Chrome, Version 84.0.4147.105 (Official Build) (64-bit)
- Operating System and version: macOS 10.14.6 (18G6020)
